INSERT INTO CUSTOMER (C_NAME,C_ADDRESS,C_CITY,C_PHONE) VALUES ('PEPITO JOSE PEREZ CARENO','CALLE 155 #15 - 24', 'BOGOTA', 3203468972);
INSERT INTO CUSTOMER (C_NAME,C_ADDRESS,C_CITY,C_PHONE) VALUES ('VILMA ROSALES MARTINEZ','CARRERA 15 #134 - 26', 'BOGOTA', 3102765629);
INSERT INTO CUSTOMER (C_NAME,C_ADDRESS,C_CITY,C_PHONE) VALUES ('ROBERTO ALVAREZ LOPEZ','CALLE 75 #26 - 16', 'BOGOTA', 3509825489);
INSERT INTO CUSTOMER (C_NAME,C_ADDRESS,C_CITY,C_PHONE) VALUES ('MARIA FERNANDA VILLA ROZO','CARRERA 7 #170 - 23', 'BOGOTA', 3150986253);
INSERT INTO CUSTOMER (C_NAME,C_ADDRESS,C_CITY,C_PHONE) VALUES ('JUNIOR ALEXIS BARRETO MENDOZA','CALLE 85 #7 - 35', 'BOGOTA', 3128572038);

INSERT INTO BANK_CARD (BC_NUMBER,BC_CCV,BC_TYPE,BC_CUSTOMER_ID_FK) VALUES ('1234 3038 4321 1121', 345, 'Tarjeta de Crédito', 1);
INSERT INTO BANK_CARD (BC_NUMBER,BC_CCV,BC_TYPE,BC_CUSTOMER_ID_FK) VALUES ('5678 3344 5612 1234', 108, 'Tarjeta de Débito', 2);
INSERT INTO BANK_CARD (BC_NUMBER,BC_CCV,BC_TYPE,BC_CUSTOMER_ID_FK) VALUES ('1121 5678 9101 1121', 2520, 'Tarjeta de Crédito', 3);
INSERT INTO BANK_CARD (BC_NUMBER,BC_CCV,BC_TYPE,BC_CUSTOMER_ID_FK) VALUES ('9101 2678 5678 9101', 3082, 'Tarjeta de Débito', 4);
INSERT INTO BANK_CARD (BC_NUMBER,BC_CCV,BC_TYPE,BC_CUSTOMER_ID_FK) VALUES ('5236 0515 1520 1121', 654, 'Tarjeta de Crédito', 5);

INSERT INTO CARD_CONSUMPTION (CC_DATE,CC_DESCRIPTION,CC_AMOUNT,CC_BANKCARD_ID_FK) VALUES(CURRENT_TIMESTAMP(), 'Compra de Televisor', 567890, 1);
INSERT INTO CARD_CONSUMPTION (CC_DATE,CC_DESCRIPTION,CC_AMOUNT,CC_BANKCARD_ID_FK) VALUES(CURRENT_TIMESTAMP(), 'Compra de Carro', 25467334, 2);
INSERT INTO CARD_CONSUMPTION (CC_DATE,CC_DESCRIPTION,CC_AMOUNT,CC_BANKCARD_ID_FK) VALUES(CURRENT_TIMESTAMP(), 'Compra de SmartPhone', 925830, 3);
INSERT INTO CARD_CONSUMPTION (CC_DATE,CC_DESCRIPTION,CC_AMOUNT,CC_BANKCARD_ID_FK) VALUES(CURRENT_TIMESTAMP(), 'Compra de Home Theather', 478392, 4);
INSERT INTO CARD_CONSUMPTION (CC_DATE,CC_DESCRIPTION,CC_AMOUNT,CC_BANKCARD_ID_FK) VALUES(CURRENT_TIMESTAMP(), 'Compra de iMac', 4782564, 5);

INSERT INTO ADVISER(A_NAME,A_SPECIALTY) VALUES('Cristina Bayona', 'Administración');
INSERT INTO ADVISER(A_NAME,A_SPECIALTY) VALUES('Erivir Arevalo', 'Gastronomia');
INSERT INTO ADVISER(A_NAME,A_SPECIALTY) VALUES('Rafael Prieto', 'Comercio');
INSERT INTO ADVISER(A_NAME,A_SPECIALTY) VALUES('Virgilio Ramirez', 'Turismo');
INSERT INTO ADVISER(A_NAME,A_SPECIALTY) VALUES('Carmen Rosales', 'Tecnologia');